"""Added columns in books table.

Revision ID: 39bee2724ccd
Revises: 3b0eacb23f53
Create Date: 2022-10-25 14:46:14.913785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39bee2724ccd'
down_revision = '3b0eacb23f53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('average_rating', sa.String(length=10), nullable=False))
    op.add_column('books', sa.Column('isbn', sa.String(length=50), nullable=False))
    op.add_column('books', sa.Column('isbn13', sa.String(length=50), nullable=False))
    op.add_column('books', sa.Column('language_id', sa.String(length=50), nullable=False))
    op.add_column('books', sa.Column('publisher_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('publication_date', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.create_unique_constraint(None, 'books', ['average_rating'])
    op.create_unique_constraint(None, 'books', ['isbn13'])
    op.create_unique_constraint(None, 'books', ['language_id'])
    op.create_unique_constraint(None, 'books', ['publication_date'])
    op.create_foreign_key(None, 'books', 'publishers', ['publisher_id'], ['id'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'publication_date')
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'language_id')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
