"""Added more columns in book table.

Revision ID: 3b0eacb23f53
Revises: 5d6907098cca
Create Date: 2022-10-25 02:14:16.233044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0eacb23f53'
down_revision = '5d6907098cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['isbn'])
    op.create_unique_constraint(None, 'books', ['average_rating'])
    op.create_unique_constraint(None, 'books', ['isbn13'])
    op.create_unique_constraint(None, 'books', ['language_id'])
    op.create_unique_constraint(None, 'books', ['publication_date'])
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'books', 'publishers', ['publisher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publication_date')
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'language_id')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###
