"""Added new models.

Revision ID: 5d6907098cca
Revises: 44ec56a4eb94
Create Date: 2022-10-25 02:12:29.354147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d6907098cca'
down_revision = '44ec56a4eb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name')
    )
    op.drop_column('books', 'publisher_id')
    op.drop_column('books', 'publication_date')
    op.drop_column('books', 'isbn13')
    op.drop_column('books', 'isbn')
    op.drop_column('books', 'average_rating')
    op.drop_column('books', 'language_id')
    op.drop_column('books', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('books', sa.Column('language_id', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('books', sa.Column('average_rating', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('books', sa.Column('isbn', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('books', sa.Column('isbn13', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('books', sa.Column('publication_date', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('books', sa.Column('publisher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('publishers')
    op.drop_table('languages')
    op.drop_table('authors')
    # ### end Alembic commands ###
