"""made books name column unique

Revision ID: 6d14907d1869
Revises: ce2f080298fb
Create Date: 2022-10-16 21:07:54.660850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d14907d1869'
down_revision = 'ce2f080298fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
