"""empty message

Revision ID: 856957a85756
Revises: 39bee2724ccd
Create Date: 2022-11-07 01:54:07.322666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856957a85756'
down_revision = '39bee2724ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('language_id', table_name='books')
    op.create_foreign_key(None, 'books', 'languages', ['language_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_index('language_id', 'books', ['language_id'], unique=False)
    # ### end Alembic commands ###
