"""Removed average rating

Revision ID: ea47df4c6a0d
Revises: 8a5837d6292d
Create Date: 2022-11-14 23:08:15.105869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea47df4c6a0d'
down_revision = '8a5837d6292d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('average_rating', table_name='books')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('average_rating', 'books', ['average_rating'], unique=False)
    # ### end Alembic commands ###
